language: android
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

android:
  components:
    - tools
    - build-tools-26.0.2
    - android-22
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22

before_script:
  - openssl aes-256-cbc -K $encrypted_c08c0a998606_key -iv $encrypted_c08c0a998606_iv -in ci-secrets.tar.gz.enc -out ci-secrets.tar.gz -d
  - tar -zxvf ci-secrets.tar.gz
  - mkdir -p $ANDROID_HOME/licenses
  - cp -r ci-secrets/licenses/* $ANDROID_HOME/licenses/
  - mv ci-secrets/google-services.json mobile/google-services.json

  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &

script:
  - ./gradlew checkstyle build connectedCheck

after_success:
  - if [ $TRAVIS_BRANCH == "develop" ]; then ./gradlew crashlyticsUploadDistributionPreRelease; fi
  - if [ $TRAVIS_BRANCH == "master" ]; then ./gradlew crashlyticsUploadDistributionBetaRelease; fi
